### ISSUE TITLE
tutorial for github

### ISSUE THREAD

**Issue by madarie** [mrrfv/cloudflare-gateway-pihole-scripts#1]
Hi,
If i understand good,this script can be installed on github?

If yes, can you please share the step by step procedure to install your script on my github account?
And also how to link cloudlfare gateway with github for the blocklist.

**Comment by madarie** [comment]
I tried to follow the steps you mentioned  for github,but it not seems to working.
No ads are bloceked? How to know if the blocklist is updated and working ?

**Comment by madarie** [comment]
I see it get failed on the step  of delete old rules and list.
Can you check if the scipt has a bug there maybe?

**Comment by madarie** [comment]
Hi,

Thanks for the reply.
Here the long error log

Skip to content
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#start-of-content>
<https://github.com/>
<https://github.com/notifications>
madarie <https://github.com/madarie>/*cg <https://github.com/madarie/cg>*
Private

   - Code <https://github.com/madarie/cg>
   - Issues <https://github.com/madarie/cg/issues>
   - Pull requests <https://github.com/madarie/cg/pulls>
   - Actions <https://github.com/madarie/cg/actions>
   - Projects <https://github.com/madarie/cg/projects>
   - Security <https://github.com/madarie/cg/security>
   - Insights <https://github.com/madarie/cg/network/dependencies>
   - Settings <https://github.com/madarie/cg/settings>

Update Filter Lists
<https://github.com/madarie/cg/actions/workflows/main.yml>
Create main.yml #1
cgps
cgps
failed 6 hours ago in 6s
Set up job
1s
Install Node.js
1s
Clone repository and switch to v1 branch
0s
Install npm dependencies
0s
Download recommended filters
2s
Delete old rules and lists
0s
1
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:1>Run
node cf_gateway_rule_delete.js
10
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:11>
11
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:12>/home/runner/work/cg/cg/cloudflare-gateway-pihole-scripts/node_modules/axios/dist/node/axios.cjs:1909

12
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:13>
reject(new AxiosError(
13
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:14>
^
14
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:15>AxiosError:
Request failed with status code 404
15
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:16>
at settle
(/home/runner/work/cg/cg/cloudflare-gateway-pihole-scripts/node_modules/axios/dist/node/axios.cjs:1909:12)

16
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:17>
at Unzip.handleStreamEnd
(/home/runner/work/cg/cg/cloudflare-gateway-pihole-scripts/node_modules/axios/dist/node/axios.cjs:2989:11)

17
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:18>
at Unzip.emit (node:events:525:35)
18
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:19>
at endReadableNT (node:internal/streams/readable:1358:12)
19
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:20>
at processTicksAndRejections (node:internal/process/task_queues:83:21) {
20
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:21>
code: 'ERR_BAD_REQUEST',
21
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:22>
config: {
22
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:23>
transitional: {
23
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:24>
silentJSONParsing: true,
24
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:25>
forcedJSONParsing: true,
25
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:26>
clarifyTimeoutError: false
26
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:27>
},
27
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:28>
adapter: [ 'xhr', 'http' ],
28
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:29>
transformRequest: [ [Function: transformRequest] ],
29
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:30>
transformResponse: [ [Function: transformResponse] ],
30
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:31>
timeout: 0,
31
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:32>
xsrfCookieName: 'XSRF-TOKEN',
32
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:33>
xsrfHeaderName: 'X-XSRF-TOKEN',
33
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:34>
maxContentLength: -1,
34
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:35>
maxBodyLength: -1,
35
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:36>
env: {
36
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:37>
FormData: [Function: FormData] {
37
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:38>
LINE_BREAK: '\r\n',
38
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:39>
DEFAULT_CONTENT_TYPE: 'application/octet-stream'
39
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:40>
},
40
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:41>
Blob: null
41
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:42>
},
42
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:43>
validateStatus: [Function: validateStatus],
43
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:44>
headers: AxiosHeaders {
44
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:45>
Accept: 'application/json, text/plain, */*',
45
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:46>
Authorization: 'Bearer ',
46
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:47>
'Content-Type': 'application/json',
47
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:48>
'X-Auth-Email': '',
48
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:49>
'X-Auth-Key': '',
49
<https://github.com/madarie/cg/actions/runs/4883222259/jobs/8714268775#step:6:50>
'User-Agent': 'axios/1.4.0',
Create new rules and lists
0s
Post Install Node.js
0s
Complete job
0s

**Comment by mrrfv** [comment]
Could you confirm that you've created the required secrets in the settings for your GitHub repository? The error you posted could indicate that the secrets aren't present.

**Comment by madarie** [comment]
Yes, I did.

**Comment by madarie** [comment]
If possible can you send a sample screen shot of the secrets how it should
be ?

**Comment by madarie** [comment]
I used the global api key from cloudflare.
In the cloudflare workers i took the cloudflare id.

Are these correct to use? Or we have to create a specific api key?

**Comment by mrrfv** [comment]
You should use the global API key, so that's correct. If you took the Cloudflare Account ID from the Workers page, that also should be good.

Could you please try running the scripts locally according to the documentation? The GitHub Action should be used after verifying locally that everything's working.

**Comment by madarie** [comment]
Have not the possibilty to test it locally.
I deleted all the file in github.created again.But still it fails on "delete old rules and list"

**Comment by kloudxyz** [comment]
I tried with my second cloudflare and github account and its working !
That great.
I wonder why my main cloudflare account and github not working.
On my main cf account, i had already created my manualy blocklist, should that be the cause?
After implementing your script, i another block list is created,should that then be an issue?

**Comment by madarie** [comment]
I tried with my second cloudflare and github account and its working !
That great.
I wonder why my main cloudflare account and github not working.
On my main cf account, i had already created my manualy blocklist, should that be the cause?
After implementing your script, i another block list is created,should that then be an issue?

**Comment by mrrfv** [comment]
It's recommended that you don't create your own blocklists in Cloudflare Zero Trust.

**Comment by madarie** [comment]
Hi,
The schedule to update the list, i understand in weekly.
Is it on saturdays or sundays? Or it starts from the day i installed the script?
And if you meanwhile get another blocklist like oisd and hagezi please do add them to script so we can autmarically get it.
