### ISSUE TITLE
Protect from ads and trackers while updating

### ISSUE THREAD

**Issue by Rovelf** [mrrfv/cloudflare-gateway-pihole-scripts#130]
Hi. Been using this script locally for almost a week and it is great. I'm planning to make another copy for the folder and rename the names/variables like "CGPS Filter Lists" into "CGPS Filter Lists 2 and "CGPS List - Chunk 1" into "CGPS List 2 - Chunk 1" so that while I'm updating (downloading the list, creating the list, and creating the rules), we're still protected from ads and trackers. After the update is done, I'll just delete the old rule and lists using the script of course. Do you know what other files needed to be rename to avoid some errors? Thanks!

**Comment by mrrfv** [comment]
Currently, the script only creates:

- Lists named `CGPS Filter Lists - Chunk *`
- Gateway rules called `CGPS Filter Lists` and optionally `CGPS Filter Lists - SNI Based Filtering`

If you don't want the script to pick up the old rules, you need to set a completely different name for them; it can't start with `CGPS`. Please keep in mind that what you're doing is unsupported, and you may run into problems such as the list limit.

**Comment by Rovelf** [comment]
> Currently, the script only creates:
> 
>     * Lists named `CGPS Filter Lists - Chunk *`
> 
>     * Gateway rules called `CGPS Filter Lists` and optionally `CGPS Filter Lists - SNI Based Filtering`
> 
> 
> If you don't want the script to pick up the old rules, you need to set a completely different name for them; it can't start with `CGPS`. Please keep in mind that what you're doing is unsupported, and you may run into problems such as the list limit.

After I renamed some words. It worked! Tried creating a bigger lists and found out that you can only upload 300 lists max even in a paid account. Went back to smaller lists.

**Comment by mrrfv** [comment]
Glad to hear that! I'll close this now. Don't hesitate to comment if you have further questions.
