### ISSUE TITLE
gaming

### ISSUE THREAD

**Issue by kakakolaka** [mrrfv/cloudflare-gateway-pihole-scripts#134]
after new update most games are not updating dinamicly ( scoreboard in cs 1.6, cs 2 is stuck, cannot type, kills doesnt show) etc etc can u fix it, it was working for months before

**Comment by kakakolaka** [comment]
fixed, dont use MASQUE, instead use Wireguard

**Comment by mrrfv** [comment]
Happy to hear you found a solution, and wrote about it in case anyone runs into the same problem. I'll close this now.
