### ISSUE TITLE
Creating IP-based lists

### ISSUE THREAD

**Issue by Rovelf** [mrrfv/cloudflare-gateway-pihole-scripts#138]
Hi. Do you know what to change to be able to download and create IP-based lists? This script only allows domains. Thanks

**Comment by mrrfv** [comment]
This isn't currently supported by the script, but you can manually set up a List and firewall rule that blocks IPs in your Cloudflare Zero Trust dashboard.

**Comment by Rovelf** [comment]
> This isn't currently supported by the script, but you can manually set up a List and firewall rule that blocks IPs in your Cloudflare Zero Trust dashboard.

woah. I didn't know you responded. Github didn't notify me. Thanks anyway
