### ISSUE TITLE
hagezi blocklist

### ISSUE THREAD

**Issue by madarie** [mrrfv/cloudflare-gateway-pihole-scripts#2]
Hi,

Can you please add hagezi Pro blocklist to the cgps script.
It is very well maintained block list.

**Comment by mrrfv** [comment]
Hagezi blocklists aren't recommended for use with CGPS because they are too big. If you try to use a Hagezi list with CGPS, it'll be trimmed to not exceed the limit of 300,000 blocked domains.

**Comment by madarie** [comment]
Oh ok.

I see you included Steven black and adaway list also.
That was my concern not to rely on only 1 blocklist provider.

Till now its working great and i am really happy with it.
Great work done by you :)

Do you know how to create a DOH profile from this zerotrust gateway for iphone?
I dont want to install the warp+ app,cause it use extra battery life.

**Comment by mrrfv** [comment]
[This](https://dns.notjakob.com/tool.html) should work

**Comment by madarie** [comment]
Wow, thanks :)
It works, you are a genius mate :)
