### ISSUE TITLE
update issues when forked

### ISSUE THREAD

**Issue by suricloud** [mrrfv/cloudflare-gateway-pihole-scripts#20]
Hi,
These days i see there are some great new updates, however with forked version we cant sync to the latest automatically anymore.
Please solve this issue,so when can sync the the latest version with no problem.

**Comment by mrrfv** [comment]
Could you please clarify what issue are you experiencing in more detail?

If I understand your problem correctly: in its default version, the CGPS GitHub Action doesn't use any files from your repository - instead, it automatically downloads the latest compatible version directly from this repo. This means that no matter how outdated your fork is, the GitHub Action will always be up to date.
However, it appears that [your fork](https://github.com/suricloud/cloudflare-gateway-pihole-scripts) gets the script files from your own repo - this means that you are responsible for updating/syncing the fork to get the latest updates.

**Comment by suricloud** [comment]
Hi,

Yes with own forked repo,when manualy  updating/syncing the the fork i had to discard all my commits.

When using the deafualt cgps version,can you tell how i can edit to set my own block and white lists? That's the only 2 files i want to edit.

Also please consider to add the following hagezi's block list;

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.normal-onlydomains.txt

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro-onlydomains.txt

**Comment by suricloud** [comment]
![Screenshot_20230918-071453](https://github.com/mrrfv/cloudflare-gateway-pihole-scripts/assets/43868361/426cca2c-fdf0-4b5d-8977-9604a987a578)
Hi,i cant sync the fork te the latest

**Comment by hlqviet** [comment]
> ![Screenshot_20230918-071453](https://user-images.githubusercontent.com/43868361/268615821-426cca2c-fdf0-4b5d-8977-9604a987a578.png) Hi,i cant sync the fork te the latest

Just delete your repo and fork a new one. Remember to save your lists.

Lists can now be defined is environment variables. Refer to README.
![image](https://github.com/mrrfv/cloudflare-gateway-pihole-scripts/assets/5486625/0ce3bc1f-e95d-4300-8ce0-1a53d3c4b97c)

**Comment by suricloud** [comment]
Hi,
Thanks for making this clear.
So this means the default blocklist and allow list will stay?
And the list i will add on variable will be added to default list?

**Comment by hlqviet** [comment]
Only your lists will be used if you add the variables.

**Comment by suricloud** [comment]
Great feature.
How can we see or share recommended  block and allow lists.

Next featue request is to auto update ip in cloudflare for location using legacy dns on routers.
Like for home,office and parrents.

There is a script,but maybe you can make it better and advanced and integrate with cgps.
https://github.com/FiorenMas/Cloudflare-Gateway-Update-DDNS-For-DNS-Locations
