### ISSUE TITLE
clean up oisd li

### ISSUE THREAD

**Issue by norbertjoni** [mrrfv/cloudflare-gateway-pihole-scripts#3]
Hello,

Thank you for your work. I am trying to use your scripts with oisd list.
Is there a good way to clean up the oisd big list? https://big.oisd.nl/

It should be done in cf_list_create.js but not sure how.

**Comment by norbertjoni** [comment]
return domain
      .replace('\r', '')
      .replace('0.0.0.0 ', '')
      .replace('127.0.0.1 ', '')
      .replace('::1 ', '')
      .replace(':: ', '')
      .replace('|| ', '')
      .replace('^ ', '')
      .replace(/^\|\|/, '')  // Remove leading '||'
      .replace(/\^$/, '');   // Remove trailing '^'

**Comment by norbertjoni** [comment]
Can I pull a new branch? the name would be: oisd

**Comment by mrrfv** [comment]
Sure! Pull requests are welcome and appreciated.

**Comment by norbertjoni** [comment]
I will do it later today.

**Comment by madarie** [comment]
i see mullvad included ois small now.

https://github.com/mullvad/dns-blocklists/tree/main/lists/doh/adblock
