### ISSUE TITLE
Regarding 300000 free limit

### ISSUE THREAD

**Issue by milindpatel63** [mrrfv/cloudflare-gateway-pihole-scripts#39]
I see that you wrote that there's a limit of 300000 blocked domains on the free account. I can't any info regarding this on cloudflare.

Also, according to this documentation https://developers.cloudflare.com/cloudflare-one/account-limits/#gateway there's a limit of 100 on Lists. And each list can only contain 1000 items. So shouldn't there be a limit of 100000 on free accounts?

Although, i tried your script via github on my cloudflare account with OISD list. It created around 187 lists without any error. I am worried if my cloudflare account will get banned for bypassing 100 limit on Lists. Is this correct?

**Comment by arunsathiya** [comment]
300000 does seem to be the correct limit. This page on the Cloudflare documentation indicates that there can be 1000 domains per list, but it doesn't explain that the maximum number of lists is 30. 
 
https://developers.cloudflare.com/cloudflare-one/policies/gateway/lists/

It's just that the script stops working after 30 lists is the indicator that a free account can have 300000.

**Comment by arunsathiya** [comment]
Oh, there is another page that seems to say that an account can have up to 100 lists. That means 1 million domains should be possible. Now I am confused.
 
https://developers.cloudflare.com/cloudflare-one/account-limits/
