### ISSUE TITLE
HTTP error! Status: 504

### ISSUE THREAD

**Issue by JuenTingShie** [mrrfv/cloudflare-gateway-pihole-scripts#45]
```
> cloudflare-delete:list
> node cf_list_delete.js

file:///home/runner/work/cloudflare-gateway-adblock/cloudflare-gateway-adblock/lib/helpers.js:40
    throw new Error(`HTTP error! Status: ${response.status}`);
          ^

Error: HTTP error! Status: 504
    at request (file:///home/runner/work/cloudflare-gateway-adblock/cloudflare-gateway-adblock/lib/helpers.js:40:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/runner/work/cloudflare-gateway-adblock/cloudflare-gateway-adblock/cf_list_delete.js:9:29
```

Hi, my github action run failed and show up this HTTP error message, it works great before.

Is there any fixable problem? What info should I provide for maintainers?

**Comment by JuenTingShie** [comment]
Addition info is that I found out my Zero Trust `team/lists` webpage takes like forever to loading, is that the reason that cause 504 status code?

**Comment by OneZK** [comment]
Cloudflare's core data center is offline due to commercial power outage and the generators failed.  Based on the latest update from cloudflarestatus.com , it says that all services has been restored but noticed in their previous update that the List (updating of list items) was temporarily suspended. It is not clear if this is the reason for error 504 since all other service such as Cloudflare API, ZT Gateway are already restored.

**Comment by OneZK** [comment]
Just to add, I have other script that will read the IP address from NO-IP and push that IP into the DNS Location in my Cloudflare Gateway account and it is now working properly. I suspect that the suspension of List (updating of list item) that was mentioned on the Cloudflare's advisory is what causing the CGPS script to fail with error 504.
Their advisory is confusing. First, they suspend the List (updating of list item) and then they provided a new update saying that "All services" has been restored and that they are now monitoring the stability.  I think they forgot to restore the List? 🤔

**Comment by mrrfv** [comment]
As @OneZK said, Cloudflare is experiencing issues on their side and this is not a problem with this project. See the [Cloudflare Status](https://www.cloudflarestatus.com/) for details. I'll keep this open just in case other people come across this.

**Comment by JuenTingShie** [comment]
Thanks for contributors' reply, I am fully understand currently status.

I'll keep re-execute my github action to see if all go back to normal, if so, then close this issue.

👍

**Comment by milindpatel63** [comment]
According to the cloudflare status page here: https://www.cloudflarestatus.com/incidents/hm7491k53ppg

> Material changes since last update: Lists have now have been moved to restored status.  Lists can only be modified through the Dashboard currently.
> Posted 13 hours ago. Nov 04, 2023 - 18:32 UTC

So, the lists should be accessible from the dashboard. But even after 13 hours now, it's still taking forever to load the lists page on the dashboard.
And on top of that, the lists loads once or twice after waiting for like several minutes and it shows that there are no lists.
I had a few other lists apart from this project, and they are gone now. Hope it gets recovered from some backup that cloudflare has in a few days.
I have raised a support ticket to cloudflare.

**Comment by OneZK** [comment]
> According to the cloudflare status page here: https://www.cloudflarestatus.com/incidents/hm7491k53ppg
> 
> > Material changes since last update: Lists have now have been moved to restored status.  Lists can only be modified through the Dashboard currently.
> > Posted 13 hours ago. Nov 04, 2023 - 18:32 UTC
> 
> So, the lists should be accessible from the dashboard. But even after 13 hours now, it's still taking forever to load the lists page on the dashboard. And on top of that, the lists loads once or twice after waiting for like several minutes and it shows that there are no lists. I had a few other lists apart from this project, and they are gone now. Hope it gets recovered from some backup that cloudflare has in a few days. I have raised a support ticket to cloudflare.

After investigating this through github and cloudflare side, I can confirm that cloudflare gateway was able to receive the domains pushed by this script based on the logs and it seems that all chunks are successfully pushed into CF gateway even though the cgps action logs shows an error on all the chunks. It sames like the CF Gateway is unable to create a Rule/Policy. Now another problem is that those chunks of domain that was pushed into cloudflare gateway wont appear when we manually create a policy with the following selector
-> Domain
-> In list
-> No Valid Options

It shows No Valid Options so it looks like those chunks becomes invisible in dashboard and through API. CGPS script cannot find those chunks when it runs the delete request to the CF API.

**Comment by erik-de-bont** [comment]
Last status from Cloudflare concerning lists

![image](https://github.com/mrrfv/cloudflare-gateway-pihole-scripts/assets/71345042/fe32f307-2390-4d2b-ae87-a59ccd1a4907)

**Comment by erik-de-bont** [comment]
Just testing now. Looks like everything is working again.

**Comment by mrrfv** [comment]
I'm still getting some unexplainable authentication issues.

**Comment by JuenTingShie** [comment]
My github action works great now. Thanks for tracing this issue.

[https://www.cloudflarestatus.com/](https://www.cloudflarestatus.com/)

![image](https://github.com/mrrfv/cloudflare-gateway-pihole-scripts/assets/31978492/6bddf574-3254-473d-90ec-e950b757e339)

**Comment by OneZK** [comment]
I think there's still a problem with  Cloudflare  API_TOKEN when FAST_MODE is Enabled. I forked a CGPS repo from someone who is using API_TOKEN instead of API_KEY. I got HTTP Error 504, 500 and 409  with FAST_MODE enabled but when FAST_MODE is disabled, everything works fine.  On the other hand, the CGPS repo that I forked directly from @mrrfv which us using API_KEY works great on both FAST_MODE enabled and disabled.
I'll investigate this issue when I have time.

**Comment by JuenTingShie** [comment]
> I think there's still a problem with Cloudflare API_TOKEN when FAST_MODE is Enabled. 

Is there any update for this situation? Just curious

**Comment by OneZK** [comment]
> > I think there's still a problem with Cloudflare API_TOKEN when FAST_MODE is Enabled.
> 
> Is there any update for this situation? Just curious

It works fine now. I ran the script with FAST_MODE enabled and it succeded without error and all chunks are created into gateway policy successfully and the old list in gateway has been deleted without error.

**Comment by JuenTingShie** [comment]
Okay, then I will close this issue. Thanks for everyone's help. :)
