### ISSUE TITLE
Getting 404 at CF Steps

### ISSUE THREAD

**Issue by umpire7777777** [mrrfv/cloudflare-gateway-pihole-scripts#56]
Hope you can help me find what I'm doing wrong.
I forked the repo, setup my secrets and variables. I'm getting a 404 error. This looks like a CF/Credential error, but I cannot figure it out :(  I run a curl test to verify the token is valid. "This API Token is valid and active"
![image](https://github.com/mrrfv/cloudflare-gateway-pihole-scripts/assets/6127818/9aee9227-3792-4cba-b8ed-0b25ee8158ff)

Pics of my repo action secrets:
![image](https://github.com/mrrfv/cloudflare-gateway-pihole-scripts/assets/6127818/35503259-49b6-4f57-a0d4-b5e2be8de977)

Pic of Variables:
![image](https://github.com/mrrfv/cloudflare-gateway-pihole-scripts/assets/6127818/17470f32-d2e1-4ffa-90f0-554b3c7e2ed1)

Log at Delete old rule and list (If I comment this step out, fails at Create). 
Run npm run cloudflare-delete
  

> cloudflare-delete
> npm run cloudflare-delete:rule && npm run cloudflare-delete:list

> cloudflare-delete:rule
> node cf_gateway_rule_delete.js

file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/lib/helpers.js:106
    throw new Error(`HTTP error! Status: ${response.status}`);
          ^

Error: HTTP error! Status: 404
    at request (file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/lib/helpers.js:106:[11](https://github.com/umpire7777777/cloudflare-gateway-pihole-scripts/actions/runs/6987216997/job/19013543830#step:7:11))
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/runner/work/cloudflare-gateway-pihole-scripts/cloudflare-gateway-pihole-scripts/cf_gateway_rule_delete.js:4:27

Node.js v[20](https://github.com/umpire7777777/cloudflare-gateway-pihole-scripts/actions/runs/6987216997/job/19013543830#step:7:21).9.0
Error: Process completed with exit code 1.

**Comment by mrrfv** [comment]
Try removing the `CLOUDFLARE_ACCOUNT_EMAIL` secret. It's not needed if you're using token authentication.

**Comment by umpire7777777** [comment]
I started without that entry and had the same error, so I tried with it.  I just removed it and have the same error.

**Comment by umpire7777777** [comment]
Resolved.  For others, the ID is NOT the userID, it's the account ID that looks like this:
5c836a76bc95766496cb94756e8675978  (this is fake)

The easiest way to find this is login to cloudflare, then this is the string after the dash URL:
https://dash.cloudflare.com/5c836a76bc95766496cb94756e8675978

Thank you!

**Comment by umpire7777777** [comment]
closing
