### ISSUE TITLE
gateway locations

### ISSUE THREAD

**Issue by madarie** [mrrfv/cloudflare-gateway-pihole-scripts#6]
Hi,
I need advice how to connect my mobile devices to cf gateway.
Should we create new dns location for evry device to get the unique dot/doh adress  ?
Are there resctrictions on the zero trust free how many device/location we can have?

**Comment by mrrfv** [comment]
You don't need to create new DNS locations for every device. I don't think there is a cap on the amount of devices you can connect to your DNS address.

**Comment by mrrfv** [comment]
Yes
